# Generated by Django 2.2 on 2019-12-25 04:29

from django.db import migrations, models
import propertypost.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to=propertypost.models.upload_update_image)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('COMMERCIAL', 'Commercial'), ('LAND', 'Land')], default='APARTMENT', max_length=150)),
                ('square', models.FloatField(default=1, verbose_name='Area in square meter?')),
                ('buyingprice', models.FloatField(blank=True, default=0, null=True, verbose_name='Buying Price?')),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('viewnum', models.IntegerField(default=0, verbose_name='view num')),
                ('pricepermeter', models.FloatField(default=0, verbose_name='Pricepermeter')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
