# Generated by Django 2.2 on 2019-12-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1500, verbose_name='title')),
                ('humantag', models.CharField(blank=True, choices=[('p', 'positive'), ('n', 'negative'), ('pn', 'neutral')], default='pn', max_length=150, null=True, verbose_name='Sentiment')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
