# Generated by Django 2.2 on 2019-12-25 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propertypost', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts4thisowner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='prop_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images4thisproperty', to='propertypost.PropertyPost'),
        ),
    ]
