# Generated by Django 2.2 on 2019-12-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertypost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='humantag',
            new_name='sentiment',
        ),
    ]
