# Generated by Django 2.2 on 2019-12-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertypost', '0002_auto_20191213_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
