# Generated by Django 2.2 on 2019-12-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.TextField(max_length=100, verbose_name='Entity')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('releventnews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities4thisnews', to='news.News')),
            ],
        ),
    ]
